version: 2.1
jobs:
  build:
    working_directory: ~/KomandaX2
    docker:
      - image: circleci/openjdk:15-jdk-buster
    steps:
      - checkout
      - run:
          name: Install Node.js and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Run tests
          command: |
            npm test -- CreateTruckerTest
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
