version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install Gradle
          command: |
            wget https://services.gradle.org/distributions/gradle-6.9-bin.zip
            sudo unzip -d /opt/gradle gradle-6.9-bin.zip
            echo 'export PATH=$PATH:/opt/gradle/gradle-6.9/bin' >> $BASH_ENV
            source $BASH_ENV
      - run: gradle build
      - run: gradle test

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build