version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build
          command: |
            javac -d build/classes src/main/java/com/example/MyClass.java
          working_directory: ~/project
      - run:
          name: Test
          command: |
            java -cp build/classes com.example.MyClassTest
          working_directory: ~/Kursinis

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build