version: 2
jobs:
  build:
    working_directory: ~/KomandaX2
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Run unit tests
          command: |
            npm install
            npm test -- --verbose
workflows:
  build_and_test:
    jobs:
      - build
