version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17.0-browsers
    steps:
      - checkout:
          path: ~/my-repo
          persist-credentials: true
          branches:
            only:
              - feature-vartotojo-regsitracija #vsfvf
      - run: npm install
      - run: npm test

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build