version: 2.1

jobs:
  build:
    docker:
      - image: circleci/maven:3.6.3-jdk-8
    steps:
      - checkout
      - run:
          name: Build
          command: mvn clean install

workflows:
  version: 2.1
  build:
    jobs:
      - build