version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17.0-browsers

    working_directory: ~/KomandaX2

    steps:
      - checkout:
          path: ~/KomandaX2
      - run: npm install
      - run: npm test CreateTruckerTest


workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build