version: 2.1
jobs:
  build:
    working_directory: ~/KomandaX2
    docker:
      - image: circleci/openjdk:15-jdk-buster
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run tests
          command: |
            npm test -- CreateTruckerTest
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
